### ISSUE TITLE
mmcv seems to be for python 3.7

### ISSUE THREAD

**Issue by jd730** [decisionforce/TPN#4]
Hi,

I ran `python set_up.py develop` the following INSTALL and run `tools/train_recognizer.py`.

I found that there are several syntax errors which seems that mmcv is programed for python 3.7. Should I use python 3.7+? Or could you specify the version of mmcv so that I can run on python 3.5.6?

Thank you.

```
Traceback (most recent call last):
  File "tools/train_recognizer.py", line 4, in <module>
    from mmcv import Config
  File "/home/jdhwang/anaconda3/envs/something/lib/python3.5/site-packages/mmcv-0.5.0-py3.5-linux-x86_64.egg/mmcv/__init__.py", line 3, in <module>
    from .arraymisc import *
  File "/home/jdhwang/anaconda3/envs/something/lib/python3.5/site-packages/mmcv-0.5.0-py3.5-linux-x86_64.egg/mmcv/arraymisc/__init__.py", line 2, in <module>
    from .quantization import dequantize, quantize
  File "/home/jdhwang/anaconda3/envs/something/lib/python3.5/site-packages/mmcv-0.5.0-py3.5-linux-x86_64.egg/mmcv/arraymisc/quantization.py", line 20
    f'levels must be a positive integer, but got {levels}')
                                                         ^
SyntaxError: invalid syntax
```

**Comment by jd730** [comment]
I found the version.
I am sorry.
